=== bowen0520/basicstudy/bd1903_xml/target/classes/day1/student.dtd
<!ELEMENT students (student*)>
<!ELEMENT student (id,name,age,describe,address)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT describe (#PCDATA)>
<!ELEMENT address (#PCDATA)>

<!ATTLIST student class_name ID #REQUIRED>
<!ATTLIST student gender (男|女) #IMPLIED>
<!ATTLIST student add CDATA #IMPLIED>
<!ATTLIST student teacher CDATA #REQUIRED>

=== bowen0520/basicstudy/bd1903_xml/target/classes/day1/test1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/css" href="test.css"?>

<!--<!DOCTYPE students SYSTEM "www.bd1903.xml.day1/student.dtd">-->
<!--
<!DOCTYPE students[
    <!ENTITY addr "江苏省苏州市昆山市学院路828号浦东软件园">
    <!ELEMENT students ANY>
    <!ELEMENT student (id,name,age,describe,address)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT describe (#PCDATA)>
    <!ELEMENT address (#PCDATA)>
]>
-->

<!DOCTYPE students SYSTEM "src\main\resources\day1\student.dtd"[
    <!ENTITY addr "江苏省苏州市昆山市学院路828号浦东软件园">
]>

<students>
    <student class_name="BDl903" teacher="b" gender="女">
        <!--学生信息-->
        <id>123</id>
        <name>zz</name>
        <age>16</age>
        <describe>成绩<![CDATA[>]]>90</describe>
        <address>&addr;</address>
    </student>

    <student class_name="BD1904" teacher="a">
        <!--学生信息-->
        <id>121</id>
        <name>bb</name>
        <age>18</age>
        <describe>成绩<![CDATA[<]]>90</describe>
        <address>&addr;</address>
    </student>

    <student class_name="BD1905" teacher="c">
        <id>122</id>
        <name>cc</name>
        <age>16</age>
        <describe>成绩&lt;90,成绩&gt;90,成绩&amp;90,成绩&apos;90,成绩&quot;90</describe>
        <address>&addr;</address>
    </student>

    <student class_name="BD1900" teacher="dqw">
        <id>123123</id>
        <name>sa</name>
        <age>12</age>
        <describe>dadsa</describe>
        <address>adsadas</address>
    </student>
</students>

=== bowen0520/basicstudy/bd1903_xml/src/main/resources/day1/newTest.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!--<?xml-stylesheet type="text/css" href="test.css"?>--><!--<!DOCTYPE students SYSTEM "www.bd1903.xml.day1/student.dtd">--><!--
<!DOCTYPE students[
    <!ENTITY addr "江苏省苏州市昆山市学院路828号浦东软件园">
    <!ELEMENT students ANY>
    <!ELEMENT student (id,name,age,describe,address)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT describe (#PCDATA)>
    <!ELEMENT address (#PCDATA)>
]>
--><students>

    <student class_name="BDl903" gender="女" teacher="b">
        <!--学生信息-->
        <id>123</id>
        <name>zz</name>
        <age>16</age>
        <describe>成绩<![CDATA[>]]>90</describe>
        <address>江苏省苏州市昆山市学院路828号浦东软件园</address>
    </student>

    

    <student class_name="BD1905" teacher="c">
        <id>122</id>
        <name>cc</name>
        <age>16</age>
        <describe>成绩&lt;90,成绩&gt;90,成绩&amp;90,成绩'90,成绩"90</describe>
        <address>江苏省苏州市昆山市学院路828号浦东软件园</address>
    </student>

    
<haha nums="10">good luck</haha></students>
